/** English copy (served at "/en"). Must keep the same shape as content/es.ts. */
import type { Content } from "./es";

export const en: Content = {
  lang: "en",
  tagline: "Software development and solutions",
  description:
    "We build, host and maintain your software. Websites, SaaS and custom systems with hosting, domain, SSL, support and maintenance included in one monthly fee.",
  nav: [
    { label: "Home", href: "#inicio" },
    { label: "Services", href: "#servicios" },
    { label: "Portfolio", href: "#portafolio" },
    { label: "About", href: "#nosotros" },
    { label: "Contact", href: "#contacto" },
  ],
  ui: {
    home: "home",
    quote: "Get a quote",
    quoteLong: "Get a quote for my project",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    toLight: "Switch to light theme",
    toDark: "Switch to dark theme",
    switchLang: "Ver en español",
    skip: "Skip to content",
    whatsapp: "Message us on WhatsApp",
    whatsappText: "Hi, I found you on kosmosdev.com and I'd like more information.",
  },
  hero: {
    badge: "Your software, in orbit",
    title: "We launch your business",
    titleHighlight: "into digital space",
    subtitle:
      "We design, build and host your website or SaaS. You focus on your business; we take care of hosting, domain, security and maintenance for a fixed monthly fee.",
    primaryCta: "See plans",
    secondaryCta: "Let's talk about your project",
    stats: [
      { value: "20+", label: "Projects delivered" },
      { value: "99.9%", label: "Uptime" },
      { value: "24/7", label: "Monitoring" },
      { value: "100%", label: "Sites with SSL" },
    ],
  },
  services: {
    eyebrow: "Services",
    title: "Monthly plans, all included",
    description: "Pick what you need. We build it, host it and keep it running.",
    popular: "Most popular",
    from: "From",
    perMonth: "/mo",
    cta: "Get started",
    note: "Every plan includes hosting, domain, SSL certificate, support and maintenance. No hidden fees.",
    items: [
      {
        icon: "Globe",
        title: "Professional website",
        description: "A fast, modern landing page or corporate site optimized for Google.",
        price: "29",
        features: ["Custom responsive design", ".com domain and SSL", "Up to 5 sections", "Contact form"],
      },
      {
        icon: "LayoutDashboard",
        title: "Custom SaaS",
        description: "Your web app on its own subdomain (app.kosmosdev.com), ready for your customers.",
        price: "149",
        from: true,
        features: ["Users and roles", "Admin dashboard", "Database and backups", "Continuous updates"],
        featured: true,
      },
      {
        icon: "Users",
        title: "CRM and management",
        description: "A system for customers, sales, inventory or appointments shaped around how you work.",
        price: "99",
        from: true,
        features: ["Customers and follow-ups", "Reports and metrics", "Access from any device", "Data export"],
      },
      {
        icon: "ShoppingCart",
        title: "Online store",
        description: "E-commerce with catalog, cart and online payments to sell around the clock.",
        price: "79",
        from: true,
        features: ["Product catalog", "Payment gateway", "Order management", "Coupons and promotions"],
      },
      {
        icon: "Server",
        title: "Managed hosting",
        description: "We migrate and host your current site on our infrastructure, fully managed.",
        price: "15",
        features: ["Domain and email", "Automatic SSL", "Daily backups", "Uptime monitoring"],
      },
      {
        icon: "Wrench",
        title: "Support and maintenance",
        description: "Changes, improvements and technical support so your system always works.",
        price: "Custom quote",
        features: ["Monthly development hours", "Bug fixes", "Security updates", "Priority support"],
      },
    ],
  },
  portfolio: {
    eyebrow: "Portfolio",
    title: "Projects already in orbit",
    description: "Some of the systems and sites we've built and still host for our clients.",
    screenshotOf: "Screenshot of",
    items: [
      {
        title: "Sales CRM",
        category: "SaaS",
        description: "Customer, opportunity and sales pipeline management for a sales team.",
        tags: ["Next.js", "PostgreSQL", "Tailwind"],
        url: "https://crm.kosmosdev.com",
        gradient: "from-indigo-500 to-cyan-400",
        icon: "Users",
      },
      {
        title: "Appointment Booking",
        category: "SaaS",
        description: "Online booking with automatic reminders for clinics and practices.",
        tags: ["React", "Node.js", "REST API"],
        gradient: "from-violet-500 to-fuchsia-400",
        icon: "LayoutDashboard",
      },
      {
        title: "Artisan Store",
        category: "E-commerce",
        description: "Online store with catalog, cart and payments for a local brand.",
        tags: ["Next.js", "Stripe", "CMS"],
        gradient: "from-amber-400 to-rose-500",
        icon: "ShoppingCart",
      },
      {
        title: "Real Estate Portal",
        category: "Web",
        description: "Property listings with filters, a map and a contact form for each property.",
        tags: ["Next.js", "Maps", "SEO"],
        gradient: "from-emerald-400 to-teal-600",
        icon: "Globe",
      },
      {
        title: "Inventory Control",
        category: "System",
        description: "Real-time stock in, stock out and alerts across several branches.",
        tags: ["TypeScript", "PostgreSQL", "Dashboard"],
        gradient: "from-sky-500 to-indigo-600",
        icon: "Database",
      },
      {
        title: "Corporate Landing",
        category: "Web",
        description: "A fast company site optimized to capture new leads.",
        tags: ["Next.js", "Tailwind", "Analytics"],
        gradient: "from-slate-600 to-slate-900",
        icon: "Rocket",
      },
    ],
  },
  about: {
    eyebrow: "About",
    title: "Your tech team, without the hassle",
    paragraphs: [
      "At Kosmos Development we build custom software and stay with you after launch. We host every project on our own infrastructure, so domain, hosting, security and updates are on us.",
      "You pay a clear, predictable monthly fee. We keep your system fast, secure and always online while your business grows.",
    ],
    values: [
      { icon: "Zap", title: "Speed", description: "Quick delivery and sites that load in seconds." },
      { icon: "ShieldCheck", title: "Security", description: "SSL, backups and updates on every project." },
      { icon: "HeartHandshake", title: "Personal", description: "Direct contact, no middlemen or endless tickets." },
      { icon: "Cloud", title: "All included", description: "Hosting, domain and support in one monthly fee." },
    ],
    techTitle: "Technologies we use",
  },
  contact: {
    eyebrow: "Contact",
    title: "Ready for liftoff?",
    description: "Tell us your idea and we'll send you a no-commitment proposal.",
    email: "Email",
    phone: "Phone",
    whatsappValue: "Message us on WhatsApp",
    location: "Location",
    locationValue: "Remote service across the Americas",
    hours: "Hours",
    hoursValue: "Monday to Friday, 9:00 to 18:00",
    form: {
      name: "Name",
      namePlaceholder: "Your name",
      email: "Email",
      emailPlaceholder: "you@email.com",
      phone: "Phone",
      optional: "(optional)",
      service: "Service of interest",
      serviceNone: "Not sure yet",
      message: "Message",
      messagePlaceholder: "Tell us about your business and what you'd like to build",
      responseTime: "We reply within one business day.",
      submit: "Send message",
      subject: "New inquiry from",
      serviceLine: "Service of interest",
      sentTitle: "Done! We opened your email",
      sentText: "Just press send in your email app. If it didn't open, write to us directly at",
      back: "Back to the form",
    },
  },
  footer: {
    navigation: "Navigation",
    services: "Services",
    contact: "Contact",
    rights: "All rights reserved.",
    madeWith: "Made with care and hosted on",
  },
};
